default['lodge']['database']['adapter'] = 'mysql2'
default['lodge']['database']['host'] = 'localhost'
default['lodge']['database']['username'] = 'root'
default['lodge']['database']['password'] = ''
default['lodge']['database']['encoding'] = 'utf8'
default['lodge']['database']['pool'] = 5
default['lodge']['environment']['production']['email']['method'] = 'sendmail'
default['lodge']['environment']['production']['smtp']['address'] = 'localhost'
default['lodge']['environment']['production']['smtp']['port'] = 25
default['lodge']['environment']['production']['smtp']['domain'] = 'localhost'
default['lodge']['environment']['production']['smtp']['username'] = nil
default['lodge']['environment']['production']['smtp']['password'] = nil
default['lodge']['environment']['production']['smtp']['authentication'] = nil
default['lodge']['environment']['production']['smtp']['enable_starttls_auto'] = true
default['lodge']['environment']['development']['email']['method'] = 'sendmail'
default['lodge']['environment']['development']['smtp']['address'] = 'localhost'
default['lodge']['environment']['development']['smtp']['port'] = 25
default['lodge']['environment']['development']['smtp']['domain'] = 'localhost'
default['lodge']['environment']['development']['smtp']['username'] = nil
default['lodge']['environment']['development']['smtp']['password'] = nil
default['lodge']['environment']['development']['smtp']['authentication'] = nil
default['lodge']['environment']['development']['smtp']['enable_starttls_auto'] = true
default['lodge']['rails']['root'] = '/var/rails/lodge'
default['lodge']['rails']['environment'] = 'production'
default['lodge']['unicorn']['user'] = 'lodge'
default['lodge']['unicorn']['worker_processes'] = 3
default['lodge']['unicorn']['timeout'] = 15
default['lodge']['unicorn']['preload_app'] = true
default['lodge']['unicorn']['listen'] = '0.0.0.0:3000'
default['lodge']['unicorn']['tcp_nopush'] = true
default['lodge']['unicorn']['stderr_path'] = default['lodge']['rails']['root'] + '/log/unicorn.stderr.log'
default['lodge']['unicorn']['stdout_path'] = default['lodge']['rails']['root'] + '/log/unicorn.stdout.log'
default['lodge']['unicorn']['pid_path'] = default['lodge']['rails']['root'] + '/tmp/unicorn.pid'
 
